package com.yb.mapper;

import com.yb.entity.Fwxx;
import com.yb.entity.FwxxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FwxxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwxx
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    long countByExample(FwxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwxx
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    int deleteByExample(FwxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwxx
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    int deleteByPrimaryKey(Integer fwid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwxx
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    int insert(Fwxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwxx
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    int insertSelective(Fwxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwxx
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    List<Fwxx> selectByExample(FwxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwxx
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    Fwxx selectByPrimaryKey(Integer fwid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwxx
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") Fwxx record, @Param("example") FwxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwxx
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    int updateByExample(@Param("record") Fwxx record, @Param("example") FwxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwxx
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    int updateByPrimaryKeySelective(Fwxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fwxx
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    int updateByPrimaryKey(Fwxx record);
}