package com.yb.entity;

import java.io.Serializable;
import java.util.Date;

public class Fwxx implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -8223067687774932103L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwxx.fwid
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    private Integer fwid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwxx.uid
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwxx.jdid
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    private Integer jdid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwxx.qxid
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    private Integer qxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwxx.lxid
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    private Integer lxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwxx.shi
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    private Integer shi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwxx.ting
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    private Integer ting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwxx.fwxx
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    private String fwxx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwxx.zj
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    private Long zj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwxx.title
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwxx.date
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwxx.telephone
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fwxx.concat
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    private String concat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwxx.fwid
     *
     * @return the value of fwxx.fwid
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public Integer getFwid() {
        return fwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwxx.fwid
     *
     * @param fwid the value for fwxx.fwid
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public void setFwid(Integer fwid) {
        this.fwid = fwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwxx.uid
     *
     * @return the value of fwxx.uid
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwxx.uid
     *
     * @param uid the value for fwxx.uid
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwxx.jdid
     *
     * @return the value of fwxx.jdid
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public Integer getJdid() {
        return jdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwxx.jdid
     *
     * @param jdid the value for fwxx.jdid
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public void setJdid(Integer jdid) {
        this.jdid = jdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwxx.qxid
     *
     * @return the value of fwxx.qxid
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public Integer getQxid() {
        return qxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwxx.qxid
     *
     * @param qxid the value for fwxx.qxid
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public void setQxid(Integer qxid) {
        this.qxid = qxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwxx.lxid
     *
     * @return the value of fwxx.lxid
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public Integer getLxid() {
        return lxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwxx.lxid
     *
     * @param lxid the value for fwxx.lxid
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public void setLxid(Integer lxid) {
        this.lxid = lxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwxx.shi
     *
     * @return the value of fwxx.shi
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public Integer getShi() {
        return shi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwxx.shi
     *
     * @param shi the value for fwxx.shi
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public void setShi(Integer shi) {
        this.shi = shi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwxx.ting
     *
     * @return the value of fwxx.ting
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public Integer getTing() {
        return ting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwxx.ting
     *
     * @param ting the value for fwxx.ting
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public void setTing(Integer ting) {
        this.ting = ting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwxx.fwxx
     *
     * @return the value of fwxx.fwxx
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public String getFwxx() {
        return fwxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwxx.fwxx
     *
     * @param fwxx the value for fwxx.fwxx
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public void setFwxx(String fwxx) {
        this.fwxx = fwxx == null ? null : fwxx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwxx.zj
     *
     * @return the value of fwxx.zj
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public Long getZj() {
        return zj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwxx.zj
     *
     * @param zj the value for fwxx.zj
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public void setZj(Long zj) {
        this.zj = zj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwxx.title
     *
     * @return the value of fwxx.title
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwxx.title
     *
     * @param title the value for fwxx.title
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwxx.date
     *
     * @return the value of fwxx.date
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwxx.date
     *
     * @param date the value for fwxx.date
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwxx.telephone
     *
     * @return the value of fwxx.telephone
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwxx.telephone
     *
     * @param telephone the value for fwxx.telephone
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fwxx.concat
     *
     * @return the value of fwxx.concat
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public String getConcat() {
        return concat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fwxx.concat
     *
     * @param concat the value for fwxx.concat
     *
     * @mbg.generated Mon Jul 29 19:13:37 CST 2019
     */
    public void setConcat(String concat) {
        this.concat = concat == null ? null : concat.trim();
    }

	@Override
	public String toString() {
		return "Fwxx [fwid=" + fwid + ", uid=" + uid + ", jdid=" + jdid
				+ ", qxid=" + qxid + ", lxid=" + lxid + ", shi=" + shi
				+ ", ting=" + ting + ", fwxx=" + fwxx + ", zj=" + zj
				+ ", title=" + title + ", date=" + date + ", telephone="
				+ telephone + ", concat=" + concat + "]";
	}
    
}